version: '3.0'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456

     wordpress:
       depends_on: 
 	 - db
       image: .
       ports:
         - 80:80
       restart: always
       enviroment:
         WORDPRESS_DB_HOST: db:3306
         WORDPRESS_DB_USER: wordpress
         WORDPRESS_DB_PASSWORD: 123456:
          volumes:
            db_data:

         
