version: '3.3'
services:
  db:
   image: mysql
   volumes:
     - db_data:/var/lib/mysql
   restart: always
   environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123456

  wordpress:
    depends_on: 
      - db
    image: .
    volumes:
      - wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123456
volumes:
    db_data:
    wordpress:

         
